# basic linting checks on master merge

name: workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
        
    steps:
    - name: MyPy check.
      run: |
        echo $(ls)
        # conda env create -f environment.yml 
        # conda activate sharptable_env
        # make check
        # make test
